package com.zak.domain.enums;

public enum NotificationTypeEnum {
    EVENT_CREATED,
    EVENT_CANCELLED,
    EVENT_UPDATED,
    EVENT_WEATHER_UPDATED,
    EVENT_COMMENTED,
    AFFECTED_TO_EVENT,
    EVENT_STARTED,
    USER_LINKED_TO_TEAM,

    RETRO_SPRINT_STATUS_UPDATED,
    RETRO_SPRINT_WEATHER_UPDATED,
    RETRO_SPRINT_COMMENT_GROUP_ADDED,
    RETRO_SPRINT_COMMENT_GROUP_DELETED,
    RETRO_SPRINT_COMMENT_GROUP_UPDATED,
    RETRO_SPRINT_COMMENT_GROUP_VOTE_ADDED,
    RETRO_SPRINT_COMMENT_GROUP_VOTE_DELETED,
    RETRO_SPRINT_COMMENT_GROUPS_VOTE_STARTED_UPDATED,

    RETRO_SPRINT_COMMENT_ADDED,
    RETRO_SPRINT_COMMENT_DELETED,
    RETRO_SPRINT_COMMENT_UPDATED,
    RETRO_SPRINT_COMMENT_DRAG_DROPPED_IN_SAME_GROUP,
    RETRO_SPRINT_COMMENT_DRAG_DROPPED_IN_OTHER_GROUP,
    RETRO_SPRINT_COMMENT_VOTE_ADDED,
    RETRO_SPRINT_COMMENT_VOTE_DELETED,
}
